//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalmia.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kalmia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ※戻り値は全て&quot;=\n {戻り値}&quot;の形式で出力
        ///
        ///quit
        ///内容:プログラム終了
        ///引数:無し
        ///エラー:無し
        ///戻り値 : 無し
        ///
        ///protocol_version
        ///内容：プロトコルバージョンを取得する
        ///引数：無し
        ///エラー：無し
        ///戻り値：プロトコルバージョンの番号
        ///
        ///name
        ///内容：プログラム名の取得
        ///引数：無し
        ///エラー：無し
        ///戻り値：プログラム名
        ///
        ///version
        ///内容：プログラムバージョンの番号の取得
        ///引数：無し
        ///エラー：無し
        ///戻り値：バージョン番号
        ///
        ///clear_board
        ///内容：盤面をクリアする
        ///引数：初期配置のタイプ &quot;cross&quot;, &quot;parallel&quot;, &quot;original&quot;のうちのどれかから選択
        ///エラー：無し
        ///戻り値：無し
        ///
        ///play
        ///内容：黒石を指定した座標に着手する
        ///引数：色 座標
        ///エラー：不正な着手が行われたとき、&quot;? illegal move&quot;と出力
        ///        不正な座標が指定されたとき、&quot;? invalid color or coordinate&quot;
        ///
        ///fixed_handicap
        ///内容：固定位置に置き石 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
    }
}
